### ISSUE TITLE
bistoury可以调试dubbo服务么？

### ISSUE THREAD

**Issue by Kratos2** [qunarcorp/bistoury#113]
我接入服务一直提示主机接入失败不是当前应用

**Comment by xleiy** [comment]
详细的情况有没，具体的日志

**Comment by Kratos2** [comment]
接入时候前端一直显示[主机校验失败，所选主机不属于该应用]

我看到ProxyServiceImpl日志里面显示services是空的 但是实际上接口是有值的  看情况貌似是没有从AppCenterServerFinder的findAgents调用到我service 里面 有点理解不明白

**Comment by Kratos2** [comment]
> 详细的情况有没，具体的日志

接入时候前端一直显示[主机校验失败，所选主机不属于该应用]

我看到ProxyServiceImpl日志里面显示services是空的 但是实际上接口是有值的 看情况貌似是没有从AppCenterServerFinder的findAgents调用到我service 里面 有点理解不明白
