### ISSUE TITLE
ui依赖zk发现存活的proxy，是否可以考虑扩展支持其它的注册中心？

### ISSUE THREAD

**Issue by SoftwareKing** [qunarcorp/bistoury#12]
ui依赖zk发现存活的proxy，是否可以考虑扩展支持其它的注册中心？比如Eureka，Nacos等

**Comment by wikiwikiwiki** [comment]
其实就bistoury来说，用到的注册中心功能很简单，后面会扩展支持其它的注册中心。
这个本来就在日程上，暂时还没来得及做...
