### ISSUE TITLE
在线debug点击无响应

### ISSUE THREAD

**Issue by cfldy** [qunarcorp/bistoury#169]
点击debug页面无响应，js报错
<img width="399" alt="image" src="https://github.com/qunarcorp/bistoury/assets/60095491/84d6dab8-e3a4-4bfd-bb7a-2f866f7dbe9c">

**Comment by fuwei199006** [comment]
这是来自QQ邮箱的自动回复邮件。
 
 来信已经收到 感谢您的来信  付威

**Comment by cfldy** [comment]
换了操作系统 agent返回的数据不是json格式,后边会多出[arthas@3935716]$,拿到数据 截断就好了
