### ISSUE TITLE
能够支持域名的么

### ISSUE THREAD

**Issue by benyVip** [qunarcorp/bistoury#20]
直接域名的访问

**Comment by wikiwikiwiki** [comment]
什么意思？是指给ui加上域名，通过域名进行访问web界面吗？

**Comment by wikiwikiwiki** [comment]
> 直接域名的访问

什么意思？是指给ui加上域名，通过域名进行访问web界面吗？

**Comment by benyVip** [comment]
是的，还有请教下8080端口启动的时候为啥会插入到h2里面？这个端口冲突会怎样呢？

**Comment by xleiy** [comment]
如果自己没有做什么定制的话，默认代码中这个端口是没有实际使用的。域名访问ui页面这个是需要自己在配置的，如果公司有ng的话，直接配置上就行。
