### ISSUE TITLE
配置后不能查看监控信息

### ISSUE THREAD

**Issue by fqtyfz** [qunarcorp/bistoury#21]
点击查看，出现一个警告，一个错误：
没有配置private token，代码查看仅可通过反编译

Agent error: java.lang.IllegalStateException---can not init bistoury, start arthas error, pid [9048],Agent JAR loaded but agent failed to initialize

还有什么配置的地方吗？

**Comment by wikiwikiwiki** [comment]
> 点击查看，出现一个警告，一个错误：
> 没有配置private token，代码查看仅可通过反编译
> 
> Agent error: java.lang.IllegalStateException---can not init bistoury, start arthas error, pid [9048],Agent JAR loaded but agent failed to initialize
> 
> 还有什么配置的地方吗？

你先加一下qq群吧，在里面更方便看问题

**Comment by xleiy** [comment]
如果在用户目录下，logs/arthas/arthas.log日志中有`can not find lib class`这样的日志，通过-c参数指定一个类，这个类要是项目里面依赖的iar包里面的，而且要是项目已经加载了的。

**Comment by wikiwikiwiki** [comment]
> 如果在用户目录下，logs/arthas/arthas.log日志中有`can not find lib class`这样的日志，通过-c参数指定一个类，这个类要是项目里面依赖的jar包里面的，而且要是项目已经加载了的。

就是这个问题，不是spring项目并且没有指定相关类名
