### ISSUE TITLE
按照 quickstart 启动成功，但是查看JVM报错如下

### ISSUE THREAD

**Issue by zhujie616** [qunarcorp/bistoury#22]
not find proxy for agent

**Comment by wikiwikiwiki** [comment]
> not find proxy for agent

你是指ui上面报这个错吧？

**Comment by xleiy** [comment]
三个原因
- agent没有连上proxy，可能是网络分区了，也可能是proxy还没有启动或启动失败了
- 机器上存在多个IP，代码获取到的ip是不可用的ip，启动时通过-i参数指定一个可用的ip
- agent注册到proxy的ip和应用中心的ip不一致，在应用中心将ip改为注册到proxy一样的ip
