### ISSUE TITLE
quick_start指定了pid,仍然是用的第一次的pid

### ISSUE THREAD

**Issue by xingfudeshi** [qunarcorp/bistoury#25]
我参考https://github.com/qunarcorp/bistoury/blob/master/docs/cn/quick_start.md,第一次启动的时候,使用./quick_start.sh -p 1234 start进行启动,然后./quick_start.sh stop停止,第二次启动我想指定另外一个进程id,于是命令改为./quick_start.sh -p 6789 start,但是"在线debug"和动态监控里面读取处理的class信息仍然是第一次的那些.

**Comment by xingfudeshi** [comment]
OS:centOS 7.2

**Comment by xleiy** [comment]
这个是和应用通信的连接获取问题，如果agent已经连接过一个应用，而且这个应用没有停止，那么连接就会一直在，那么下次agent就不会重新建立连接，会复用这个连接，现在的处理方式可以把应用重启下，或者在命令行交互页面执行一下shutdown命令，后续我们看下怎么处理这个问题

**Comment by xingfudeshi** [comment]
> 这个是和应用通信的连接获取问题，如果agent已经连接过一个应用，而且这个应用没有停止，那么连接就会一直在，那么下次agent就不会重新建立连接，会复用这个连接，现在的处理方式可以把应用重启下，或者在命令行交互页面执行一下shutdown命令，后续我们看下怎么处理这个问题

好的.谢谢
