### ISSUE TITLE
ApplicationUserDaoImpl 的 bistoury_user_app表插入SQL有语法错误

### ISSUE THREAD

**Issue by KatyConnor** [qunarcorp/bistoury#26]
类： ApplicationUserDaoImpl

private static final String ADD_USER_FOR_APP = "insert ignore bistoury_user_app (app_code, user_code) values (?, ?)";

这个SQL少了一个 into 关键字。

**Comment by xleiy** [comment]
已修复 [tag v2.0.3](https://github.com/qunarcorp/bistoury/tree/v2.0.3)
