### ISSUE TITLE
bistoury-proxy 启动建议

### ISSUE THREAD

**Issue by xkrivzooh** [qunarcorp/bistoury#3]
`bistoury-proxy`模块中的`Bootstrap`类中对`webapp`路径的获取不太友好，完全依赖用户从什么目录下执行`bistoury-proxy.sh`。

```java
String webappDirLocation = "../webapp/";
            StandardContext ctx = (StandardContext) tomcat.addWebapp("/", new File(webappDirLocation).getAbsolutePath());
```
这种写法相当于强制用户必须在`bistoury-proxy/bin/`目录下执行`./bistoury-proxy.sh start`命令。
使得像`./bin/bistoury-proxy.sh start`之类的命令都不能使用。因为会导致获取不到`webapp`的正确路径。

感觉应该在shell脚本中获取当前的bistoury-proxy的HOME地址，然后基于`BISTOURY-PROXY-HOME/webapp`来读取会更好一些。

**Comment by xleiy** [comment]
webapp路径获取方式已修改[00d684109e7a5dba4ca362604a8d76bb34342ddc](https://github.com/qunarcorp/bistoury/commit/00d684109e7a5dba4ca362604a8d76bb34342ddc)

使用启动类的路径，反推webapp的路径
