### ISSUE TITLE
在线debug遇到断点添加失败

### ISSUE THREAD

**Issue by waterman1009** [qunarcorp/bistoury#32]
在线debug页面点击添加断点的时候报错，显示register breakpoint fail, File was not found in the executable。使用的是quick-start，本机启动。
![image](https://user-images.githubusercontent.com/11442587/64012500-698a3c00-cb50-11e9-8081-8e3e9a679cc7.png)

**Comment by xleiy** [comment]
在启动应用的用户目录下/logs/bistoury/bistoury.log中找到`Initializing ClassPathLookup, default classpath`开始的日志，你检查下你的lib目录和classes目录在没在下面。
如果你是springboot项目，并且是使用idea直接运行main方法运行的，可以使用tomcat运行，或者打包为jar包之后直接使用用jar包启动

**Comment by niejian** [comment]
使用web-assemble 打包，将lib目录分开，这种添加不了断点该怎么解决呢

**Comment by bigfish1913** [comment]
这是来自QQ邮箱的自动回复邮件。
 
 来信已经收到 感谢您的来信  付威
