### ISSUE TITLE
在线debug时，弹出请检查主机上是否存在releaseInfo.properties 文件，看了下是没有的

### ISSUE THREAD

**Issue by markflyfly** [qunarcorp/bistoury#42]
/tmp/bistoury/releaseInfo.properties

**Comment by wikiwikiwiki** [comment]
> /tmp/bistoury/releaseInfo.properties

这只是个默认值，实际上应该是应用自身发布的时候提供的，具体这方面我们会更新个文档说明，稍等一下

**Comment by xleiy** [comment]
这个文件是应用的发布信息，一般是有发布系统在发布是输出的。这个文件的主要作用是结合git查看源码使用。[git配置](https://github.com/qunarcorp/bistoury/blob/master/docs/cn/gitlab_maven.md)
