### ISSUE TITLE
Private token 点击链接获取提示 "页面跳转失败，请联系管理员检查配置文件"

### ISSUE THREAD

**Issue by hedleyyan** [qunarcorp/bistoury#44]
通过 quick_start.sh 启动

**Comment by xleiy** [comment]
这种跳转的链接配置全部在`bistoury-ui/conf/url_redirect.properties`中，点击这些链接时，后端会根据key找到对应的链接进行跳转，当跳转的key找不到或值为空时，会跳转到这个错误页面。
