### ISSUE TITLE
在线debug功能查看到的加载类不全

### ISSUE THREAD

**Issue by hedleyyan** [qunarcorp/bistoury#46]
比如 java 库中的 Integer 、String 类都看不到加载，程序的源码类也都看不到
Thread Dump 里的信息确认完整。堆对象统计信息确认完整。
请问是哪里出了问题，多谢

BTW , great job!

**Comment by wikiwikiwiki** [comment]
> 比如 java 库中的 Integer 、String 类都看不到加载，程序的源码类也都看不到
> Thread Dump 里的信息确认完整。堆对象统计信息确认完整。
> 请问是哪里出了问题，多谢
> 
> BTW , great job!

修改这些核心类的风险太大了，我们过滤了所有由bootstrap classloader加载的类

**Comment by hedleyyan** [comment]
@wikiwikiwiki 明白，但是我们程序的源码类为何也看不到呢
![image](https://user-images.githubusercontent.com/6184086/64608498-64a17400-d3fd-11e9-8285-2f383e7cc8df.png)

**Comment by wikiwikiwiki** [comment]
> @wikiwikiwiki 明白，但是我们程序的源码类为何也看不到呢
> ![image](https://user-images.githubusercontent.com/6184086/64608600-9dd9e400-d3fd-11e9-9b07-0997ad65a3be.png)
> 
> 启动时可以手动指定 attach 的 classloader 吗

如果是脚本启动可以-c指定一个你的应用依赖的jar包中已被加载的类，不是脚本启动可以指定系统参数bistoury.app.lib.class（注意是要在attach前已经加载的类，如果是后面才加载的类，可以在在线debug类列表页面点击重新加载）。我们通过这个类来查找应用的classloader。默认是spring的DispatcherServlet。
在线debug能看到的类是你程序中已经加载的类，你这种情况是不是类没加载
