### ISSUE TITLE
在在线debug中，怎么使用gitlab获取源码，而不是使用maven获取源码

### ISSUE THREAD

**Issue by EsmeraldaYS** [qunarcorp/bistoury#47]
在在线debug中，怎么使用gitlab获取源码，而不是使用maven获取源码。按照文档的说法，这是可行的，但是我把maven.nexus.url 这个配置注释后，看ui的日志文件依然使用MavenRepositoryServiceImpl获取

**Comment by wikiwikiwiki** [comment]
现在是会有无效的请求，这个地方我们会优化下

**Comment by xleiy** [comment]
源码获取逻辑是这样的，先尝试从git获取源码，获取不到时尝试从maven获取源码，再获取不到时会进行反编译，只要你debug的类的是jar包中的，且这个jar包中有maven信息，我们就会尝试从maven获取。

我们现在的优化方案就是如果没有配置`maven.nexus.url`，我们就提前返回，如果你想直接不发生这个请求，就需要你们自己定制一下，在前端把发送请求的地方处理掉。
