### ISSUE TITLE
bistoury-agent-bin/bin/bistoury-agent-env.sh中的BISTOURY_PROXY_HOST也需要改端口吧

### ISSUE THREAD

**Issue by xianwei** [qunarcorp/bistoury#48]
bistoury-agent-bin/bin/bistoury-agent-env.sh中的BISTOURY_PROXY_HOST也需要改端口吧

**Comment by xleiy** [comment]
en，[文档已修改](https://github.com/qunarcorp/bistoury/blob/master/docs/cn/FAQ.md#%E7%AB%AF%E5%8F%A3%E9%97%AE%E9%A2%98)
