### ISSUE TITLE
启动不了

### ISSUE THREAD

**Issue by gfhn** [qunarcorp/bistoury#49]
![image](https://user-images.githubusercontent.com/38518587/65033379-75129b00-d977-11e9-80aa-af283f8866dc.png)
想问一下，这个脚本是怎么修改呢？路径改了之后运行就变成这个样子了

**Comment by xleiy** [comment]
脚本需要使用的bash运行，Ubuntu使用的是dash，还有就是检查下文件的读、写、执行权限
