### ISSUE TITLE
启动报错！！！！请教咋回事呢

### ISSUE THREAD

**Issue by jya126** [qunarcorp/bistoury#53]
版本：bistoury-2.0.6-quick-start.tar.gz
环境：Ubuntu 16.04.2 LTS \n \l        java version "1.8.0_101"，启动报错
./quick_start.sh: 84: ./quick_start.sh: [[: not found
./quick_start.sh: 88: ./quick_start.sh: [[: not found
./quick_start.sh: 93: ./quick_start.sh: [[: not found
./quick_start.sh: 97: ./quick_start.sh: [[: not found
./quick_start.sh: 103: ./quick_start.sh: [[: not found
命令格式错误，Usage: [./quick_start.sh -p pid -j java_home start] or [./quick_start.sh stop]
加上java_home 同样错误

**Comment by xleiy** [comment]
脚本运行需要使用bash，但是Ubuntu使用的是dash，使用bash quick_start.sh运行脚本
