### ISSUE TITLE
建议在线debug增加按照不同类型变量查找的功能

### ISSUE THREAD

**Issue by wallezhang** [qunarcorp/bistoury#56]
在线debug遇到变量比较多，或者变量内容比较大的时候，想找到自己关注的变量比较困难，通过浏览器自带的搜索功能，可能会搜索到代码中的变量名字，建议增加查找功能，直接定位到变量所在的位置

**Comment by xleiy** [comment]
好的，下次发布带上。

**Comment by wallezhang** [comment]
> 好的，下次发布带上。

或者我可以提PR

**Comment by xleiy** [comment]
也可以
