### ISSUE TITLE
agent连接proxy超时

### ISSUE THREAD

**Issue by AlexJialene** [qunarcorp/bistoury#57]
启动./quick_start.sh -p 10684 start 时，agent.out 抛出TimeoutException:
java.util.concurrent.TimeoutException: Request timed out to /127.0.0.1:9090 of 3000 ms
---------------------------
应用部署在同一服务器。
好像是agent 启动 bistoury netty client 请求proxy for agent config 时proxy还未启动完成

**Comment by xleiy** [comment]
这个会在30s内进行重试

**Comment by eternalstone** [comment]
127.0.0.1:9090服务已经成功了，可以看到HelloWorld，但是agent还是不断的报TimeoutException: Request timed out to /127.0.0.1:9090 of 3000 ms

**Comment by ljzforever** [comment]
Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [52,183] milliseconds.

我这proxy启用用了近52秒，超时

**Comment by awesometype** [comment]
这也没说解决方案啊，就close了
