### ISSUE TITLE
 java.lang.IllegalArgumentException: Process not found

### ISSUE THREAD

**Issue by hadesvip** [qunarcorp/bistoury#60]
在浏览器中返问  bistoury ui 项目的时候，出现如下错误
Agent error: java.lang.RuntimeException---java.lang.RuntimeException:
Cannot perf data for process 1000 - java.lang.IllegalArgumentException: Process not found

我系统是ubuntu，我启动的命令是bash quick_start.sh -p1000 start
直接使用quick_start.sh start会报如下错误 
➜  bistoury bash quick_start.sh start
没有指定-c参数，agent将通过org.springframework.web.servlet.DispatcherServlet获取应用jar包路径

**Comment by hadesvip** [comment]
我看了下proc目录下的确没有1000文件

**Comment by xleiy** [comment]
-p参数后面跟的是你要诊断的java应用的pid，你需要指定争取的pid，你先检查下你的机器上有这个java进程吗

**Comment by hadesvip** [comment]
我的问题，的确是进程不存在
