### ISSUE TITLE
proxy 报非法数据异常

### ISSUE THREAD

**Issue by GuanTu** [qunarcorp/bistoury#66]
agent在Docker容器内，proxy在物理机上。agent启动时proxy会报“非法数据”

![image](https://user-images.githubusercontent.com/22937069/70905936-217c2000-2040-11ea-855e-dcd7b319e435.png)

**Comment by xleiy** [comment]
可以检查下agent和ui的日志，看是不是端口填错了，导致把http的请求打到netty的端口上去了，端口详情见[端口说明](https://github.com/qunarcorp/bistoury/blob/master/docs/cn/FAQ.md#%E7%AB%AF%E5%8F%A3%E9%97%AE%E9%A2%98)

**Comment by GuanTu** [comment]
已解决，应该对应proxy的http端口 9090
