### ISSUE TITLE
ubuntu16启动报错 求解

### ISSUE THREAD

**Issue by wh51665526** [qunarcorp/bistoury#75]
![image](https://user-images.githubusercontent.com/20767730/76383021-815f3a00-6395-11ea-8e1f-b16f73435900.png)
尝试了使用bash 执行还是不行，求解，谢谢

**Comment by xleiy** [comment]
你用这个命令替换下bistoury相关脚本内容：find . -name "*.sh" | xargs sed -i 's@^#!/bin/sh@#!/bin/bash@g'
