### ISSUE TITLE
maven 打包失败

### ISSUE THREAD

**Issue by erzhen-wu** [qunarcorp/bistoury#82]
[ERROR] Failed to execute goal on project bistoury-common: Could not resolve dependencies for project qunar.tc.bistoury:bistoury-common:jar:2.0.6: Failed to collect dependencies at com.google.guava:guava:jar:20.0: Failed to read artifact descriptor for com.google.guava:guava:jar:20.0: Could not transfer artifact com.google.guava:guava:pom:20.0 from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/com/google/guava/guava/20.0/guava-20.0.pom: Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.52.215] failed: Connection refused (Connection refused) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :bistoury-common
================ building bistoury proxy finished ================

**Comment by orangle** [comment]
上面提示的不是很明显么？ 或者上面的提示不是真正的原因？
