### ISSUE TITLE
k8s部署后，agent 上报信息中IP地址为集群中宿主机docker0 地址，而不是pod的 cluster-ip 

### ISSUE THREAD

**Issue by windghoul** [qunarcorp/bistoury#85]
![image](https://user-images.githubusercontent.com/16053291/83216891-f2480e00-a19c-11ea-9714-8188f3c3e24f.png)
![image](https://user-images.githubusercontent.com/16053291/83216944-0855ce80-a19d-11ea-822b-5f86f308ae6e.png)
![image](https://user-images.githubusercontent.com/16053291/83216986-21f71600-a19d-11ea-959d-5f18c6696af1.png)

**Comment by xleiy** [comment]
明天发版，之后的版本可以通过-Dbistoury.local.host参数指定ip

**Comment by windghoul** [comment]
> 明天发版，之后的版本可以通过-Dbistoury.local.host参数指定ip

thanks

**Comment by windghoul** [comment]
找到问题所在，proxy 将自己所在的宿主机的docker0 IP地址作为agent 的地址上报了，proxy 是设置了-Dbistoury.local.host 参数的，这种有没有办法解决？

**Comment by xleiy** [comment]
proxy现在获取agent的ip是通过netty的chanel获取的，后续版本会直接将agent指定的ip上报到proxy
